@startuml

title 假想关键字then的状态转换图

hide empty description

state " " as 1
state " " as 2
state " " as 3
state " " as 4
state " " as 5
state "*" as 6

[*] -> 1: start
1 -> 2: t
2 -> 3: h
3 -> 4: e
4 -> 5: n
5 -> 6: nonlet/dig

@enduml