#pragma once

// generated by /home/test/opensrc/sqlpp11/sqlpp11/scripts/ddl2cpp student.sql student student

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace student
{
  namespace TableStudent_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Number
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "number";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T number;
            T& operator()() { return number; }
            const T& operator()() const { return number; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Gender
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "gender";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T gender;
            T& operator()() { return gender; }
            const T& operator()() const { return gender; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace TableStudent_

  struct TableStudent: sqlpp::table_t<TableStudent,
               TableStudent_::Id,
               TableStudent_::Number,
               TableStudent_::Name,
               TableStudent_::Gender>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "table_student";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tableStudent;
        T& operator()() { return tableStudent; }
        const T& operator()() const { return tableStudent; }
      };
    };
  };
  namespace TableClass_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct Name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T name;
            T& operator()() { return name; }
            const T& operator()() const { return name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace TableClass_

  struct TableClass: sqlpp::table_t<TableClass,
               TableClass_::Id,
               TableClass_::Name>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "table_class";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tableClass;
        T& operator()() { return tableClass; }
        const T& operator()() const { return tableClass; }
      };
    };
  };
  namespace TableStudentClassRel_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct StudentId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "student_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T studentId;
            T& operator()() { return studentId; }
            const T& operator()() const { return studentId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct ClassId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "class_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T classId;
            T& operator()() { return classId; }
            const T& operator()() const { return classId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace TableStudentClassRel_

  struct TableStudentClassRel: sqlpp::table_t<TableStudentClassRel,
               TableStudentClassRel_::Id,
               TableStudentClassRel_::StudentId,
               TableStudentClassRel_::ClassId>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "table_student_class_rel";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tableStudentClassRel;
        T& operator()() { return tableStudentClassRel; }
        const T& operator()() const { return tableStudentClassRel; }
      };
    };
  };
} // namespace student
